site_name: Tinkoff ID Документация
theme:
  name: material
  language: 'ru'
  logo: img/logo.png


  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.tabs.link
    - navigation.instant
  
  palette:
    - scheme: slate
      primary: amber
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: default
      primary: amber
      accent: indigo
      toggle:
         icon: material/toggle-switch-off-outline
         name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables


nav:    
  - Обзор: index.md
  - Менеджеру:
    - Преимущества: adv.md
    - Описание продукта: managers.md
    - Связанные решения: cross.md
    - Как подключить сервис: join.md
  - Разработчику: 
    - Авторизация web2web: w2w.md
    - Авторизация app2web: a2w.md
    - Мобильная авторизация: mobile.md
    - Ссылочная авторизация: link-auth.md
    - Tinkoff ID Widget Button: widget-button.md
    - Tinkoff ID Widget White Label: widget-white-label.md
    - Tinkoff ID Widget Notification: widget-notification.md
    - Tinkoff ID  Bitrix: bitrix.md
    - Tinkoff ID  WordPress: wordpress.md
    - Работа с полученными токенами: tokens.md
    - Метчинг учеток: matching.md
    - Тестирование: testing.md
  - Делегированная идентификация:
    - Делегированная идентификация в рамках 115 ФЗ: identity.md
    - Получить паспортные данные по 115 ФЗ: passport_short.md
    - Получить паспортные данные: ident_passport.md
    - Получить признак публичного должностного лица: pdl.md
    - Получить признак иностранного агента: foreignagent.md
    - Проверка наличия в чёрных списках: blacklist.md
    - Получить информацию об идентификации пользователя: ident_identification.md
    - Получить адреса: ident_addresses.md
    - Тестирование: testing_ident.md
  - Методы:
    - Информация о пользователе: userinfo.md
    - Получить паспортные данные: passport.md
    - Получить водительские удостоверения: driverlicenses.md
    - Получить ИНН: inn.md
    - Получить СНИЛС: snils.md
    - Получить статус самозанятого: selfemployed.md
    - Получить информацию об активных дебетовых счетах: debit.md
    - Получить информацию об активной подписке клиента: subscription.md
    - Получить информацию об идентификации пользователя: identification.md
    - Получить адреса: addresses.md
    - Тестирование: testing_metod.md
  - FAQ: 
    - Часто задаваемые вопросы: faq.md
    - Глоссарий: glossary.md

